### ISSUE TITLE
Extension not replacing anything

### ISSUE THREAD

**Issue by guidezpl** [ajayyy/DeArrow#299]
I've activated the extension, and even tried it in an incognito window with no other extensions enabled, and no replacement is happening.

```
0 titles and 0 thumbnails have been replaced since you installed this extension
```

Any troubleshooting steps?

**Comment by ajayyy** [comment]
Can you go to options > misc > copy debug info

**Comment by guidezpl** [comment]
```
{
    "debug": {
        "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
        "platform": "MacIntel",
        "language": "en",
        "extensionVersion": "1.8"
    },
    "config": {
        "activated": true,
        "allowExpirements": true,
        "alreadyActivated": true,
        "alwaysShowShowOriginalButton": true,
        "darkMode": true,
        "firefoxOldContentScriptRegistration": false,
        "importedConfig": true,
        "lastIncognitoStatus": true,
        "showActivatedMessage": true,
        "showDonationLink": true,
        "showInfoAboutRandomThumbnails": true,
        "showUpsells": true,
        "thumbnailReplacements": 2,
        "vip": false,
        "donateClicked": 0,
        "invidiousInstances": 0,
        "keepUnsubmitted": true,
        "keepUnsubmittedInPrivate": false,
        "thumbnailSaturationLevel": 100,
        "titleFormatting": 1,
        "shouldCleanEmojis": true,
        "onlyTitleCaseInEnglish": false,
        "serverAddress": "Default server address",
        "thumbnailServerAddress": "https://dearrow-thumb.ajay.app",
        "fetchTimeout": 7000,
        "startLocalRenderTimeout": 2000,
        "renderTimeout": 25000,
        "thumbnailCacheUse": 2,
        "showGuidelineHelp": true,
        "thumbnailFallback": 0,
        "thumbnailFallbackAutogenerated": 0,
        "showLiveCover": true,
        "extensionEnabled": true,
        "defaultToCustom": true,
        "showOriginalOnHover": false,
        "replaceTitles": true,
        "replaceThumbnails": true,
        "useCrowdsourcedTitles": true,
        "titleMaxLines": 3,
        "channelOverrides": {},
        "customConfigurations": {},
        "showIconForFormattedTitles": true,
        "countReplacements": true,
        "titleReplacements": 0,
        "ignoreAbThumbnails": true,
        "hideDetailsWhileFetching": true,
        "firstThumbnailSubmitted": false,
        "freeTrialDuration": 21600000,
        "freeAccessWaitingPeriod": 259200000,
        "openMenuKey": {
            "key": "d",
            "shift": true
        },
        "enableExtensionKey": {
            "key": "e",
            "ctrl": true,
            "shift": true,
            "alt": true
        }
    }
}
```

**Comment by koiz-koiz** [comment]
I've had a similar problem, and i think it may be caused by a UI experiment
![image](https://github.com/user-attachments/assets/6c6772eb-d4ff-4691-99a8-6e0515025b1e)
![image](https://github.com/user-attachments/assets/fa8b78a1-924f-4694-888c-5ee2a802878a)
dearrow works on pages where the upload button on the masthead is just the icon, but doesn't when it's the button marked "create"

**Comment by koiz-koiz** [comment]
okay upon further inspection, the experiment is having the masthead and chipbar be translucent, like ambient mode.
using inspect element the experiment consists of 2 parts, backdrop-filter-experiment and button-shape-next
![image](https://github.com/user-attachments/assets/241107d0-adc3-43bb-bc95-bab04fc1bc86)

**Comment by mrinmaydhar** [comment]
Facing the same issue. It's not replacing on the front page (except for the "Tell us what you like" section). However, it works when a video is opened.

> Can you go to options > misc > copy debug info

```
{
    "debug": {
        "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0",
        "platform": "Win32",
        "language": "en-IN",
        "extensionVersion": "1.8"
    },
    "config": {
        "allowExpirements": true,
        "alreadyActivated": true,
        "alwaysShowShowOriginalButton": true,
        "darkMode": true,
        "extensionEnabled": true,
        "firefoxOldContentScriptRegistration": false,
        "importedConfig": true,
        "lastIncognitoStatus": false,
        "lastVersion": "1.2.10",
        "replaceThumbnails": true,
        "replaceTitles": true,
        "showDonationLink": false,
        "showUpsells": true,
        "thumbnailReplacements": 360843,
        "titleReplacements": 55140,
        "vip": false,
        "donateClicked": 0,
        "invidiousInstances": 0,
        "keepUnsubmitted": true,
        "keepUnsubmittedInPrivate": false,
        "thumbnailSaturationLevel": 100,
        "titleFormatting": 1,
        "shouldCleanEmojis": true,
        "onlyTitleCaseInEnglish": false,
        "serverAddress": "Default server address",
        "thumbnailServerAddress": "https://dearrow-thumb.ajay.app",
        "fetchTimeout": 7000,
        "startLocalRenderTimeout": 2000,
        "renderTimeout": 25000,
        "thumbnailCacheUse": 2,
        "showGuidelineHelp": true,
        "thumbnailFallback": 0,
        "thumbnailFallbackAutogenerated": 0,
        "showLiveCover": true,
        "defaultToCustom": true,
        "showOriginalOnHover": false,
        "useCrowdsourcedTitles": true,
        "titleMaxLines": 3,
        "channelOverrides": {},
        "customConfigurations": {},
        "showInfoAboutRandomThumbnails": false,
        "showIconForFormattedTitles": true,
        "countReplacements": true,
        "ignoreAbThumbnails": true,
        "hideDetailsWhileFetching": true,
        "firstThumbnailSubmitted": false,
        "activated": true,
        "freeTrialDuration": 21600000,
        "freeAccessWaitingPeriod": 259200000,
        "showActivatedMessage": false,
        "openMenuKey": {
            "key": "d",
            "shift": true
        },
        "enableExtensionKey": {
            "key": "e",
            "ctrl": true,
            "shift": true,
            "alt": true
        }
    }
}
```

**Comment by ajayyy** [comment]
Can you save the page with Ctrl s and email it to dev @ ajay.app

**Comment by mrinmaydhar** [comment]
@ajayyy sent.

**Comment by mrinmaydhar** [comment]
Hello @ajayyy, apologies for the ping, but just wanted to confirm if you received the mail. I have been a victim of email spoofing, so most of my mails get sent to junk/spam by mail providers.

**Comment by RandomAnimeGamer** [comment]
I'm having an issue where the front page isn't loading any of the updated thumbnails. If I disable DeArrow from its own menu, the original thumbnails partially load. If I disable the extension period, the original thumbnails load immediately.
{
    "debug": {
        "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 OPR/113.0.0.0 (Edition std-1)",
        "platform": "Win32",
        "language": "en-US",
        "extensionVersion": "1.8"
    },
    "config": {
        "activated": true,
        "alreadyActivated": true,
        "extensionEnabled": true,
        "firefoxOldContentScriptRegistration": false,
        "firstThumbnailSubmitted": true,
        "lastIncognitoStatus": false,
        "showActivatedMessage": true,
        "showInfoAboutRandomThumbnails": false,
        "thumbnailReplacements": 92914,
        "titleReplacements": 16575,
        "vip": false,
        "allowExpirements": true,
        "showDonationLink": true,
        "showUpsells": true,
        "donateClicked": 0,
        "darkMode": true,
        "invidiousInstances": 0,
        "keepUnsubmitted": true,
        "keepUnsubmittedInPrivate": false,
        "thumbnailSaturationLevel": 100,
        "titleFormatting": 1,
        "shouldCleanEmojis": true,
        "onlyTitleCaseInEnglish": false,
        "serverAddress": "Default server address",
        "thumbnailServerAddress": "https://dearrow-thumb.ajay.app",
        "fetchTimeout": 7000,
        "startLocalRenderTimeout": 2000,
        "renderTimeout": 25000,
        "thumbnailCacheUse": 2,
        "showGuidelineHelp": true,
        "thumbnailFallback": 0,
        "thumbnailFallbackAutogenerated": 0,
        "showLiveCover": true,
        "defaultToCustom": true,
        "alwaysShowShowOriginalButton": false,
        "showOriginalOnHover": false,
        "importedConfig": false,
        "replaceTitles": true,
        "replaceThumbnails": true,
        "useCrowdsourcedTitles": true,
        "titleMaxLines": 3,
        "channelOverrides": {},
        "customConfigurations": {},
        "showIconForFormattedTitles": true,
        "countReplacements": true,
        "ignoreAbThumbnails": true,
        "hideDetailsWhileFetching": true,
        "freeTrialDuration": 21600000,
        "freeAccessWaitingPeriod": 259200000,
        "openMenuKey": {
            "key": "d",
            "shift": true
        },
        "enableExtensionKey": {
            "key": "e",
            "ctrl": true,
            "shift": true,
            "alt": true
        }
    }
}

**Comment by ajayyy** [comment]
Looks like they've changed how the entire page is rendered, all the elements are changed

**Comment by ajayyy** [comment]
Could someone email me the HTML for the watch page of a video if that is broken as well?

dev @ ajay.app

**Comment by ajayyy** [comment]
Fixed it for the homepage, will need the related videos to make sure it works there too

**Comment by ajayyy** [comment]
Managed to get a session with the related pages acting up and a fix will be in `1.9.1` release

**Comment by guidezpl** [comment]
@ajayyy  This issue is still occurring in 2.1.0. I'll send a few HTML files to help
